### PR TITLE
chore: gatsby v4 update

### PR DESCRIPTION
**Pull request by NickyMeuleman**
- [x] update gatsby to v4
- [x] use gatsby head instead of react-helmet
- [x] update mdx
- [x] update theme-ui
- [x] update eslint

### CODE REVIEW

**Comment by NickyMeuleman** [comment]
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#updating-page-templates

**Comment by NickyMeuleman** [comment]
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#migrating-from-v3-to-v4

**Comment by NickyMeuleman** [comment]
https://github.com/LekoArts/gatsby-themes/pull/967

**Comment by NickyMeuleman** [comment]
Codeblocks don't get any props apart from a classname with `language-X` passed to them.
As a result, the `<CodeBlock>` component does not work.

The earliest part where this data should flow that is doesn't is in `components/mdx-components.tsx`.

I copied the logic from @LekoArts https://github.com/LekoArts/gatsby-themes/blob/main/themes/gatsby-theme-minimal-blog/src/components/mdx-components.tsx

When logging out `preProps` there, a React element gets logged with only `children` (the codestring), and a `classname` (in the form of language-X` in there.

This is on a block like this:
\```js hl numberLines
const test = "potato"
\```

**Comment by LekoArts** [comment]
I was also curious about this at first since it worked before. But this must have changed with MDX 2. Anyways, I looked at their guide https://mdxjs.com/guides/syntax-highlighting/#syntax-highlighting-with-the-meta-field and then adjusted it for my needs.

TS version: https://github.com/LekoArts/gatsby-themes/tree/main/packages/rehype-meta-as-attributes
JS version (easier to copy/paste): https://github.com/LekoArts/portfolio-v2/tree/main/packages/rehype-meta-as-attributes

Then put the plugin into the `mdxOptions`:

```js
rehypePlugins: [rehypeMetaAsAttributes]
```

Afterwards the props will go through again. My code is adjusted from the MDX guide since I want to receive `true` when only the prop is given, not `''`

**Comment by NickyMeuleman** [comment]
Gatsby head notes:
- You can only define the Head export inside a page, not in a component.
	- results in: every `SomethingPage` component needs to export a `Head` that is then used in the templates called `SomethingQuery`.

- Valid tags inside the Head function are: link, meta, style, title, base, script, and noscript.
	- results in: handling the `defaultTitle` and `titleTemplate` currently there from react-helmet yourself first when building the `<title>`.
	- results in: handling the `<html>` `lang` differently. Probably setting it in a `gatsby-X.js` file
	edit: yup, see: https://github.com/LekoArts/gatsby-themes/blob/ee969f30037fa99232292014431854773735d0a0/examples/minimal-blog/gatsby-ssr.js

**Pull request merged**
